version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    ports:
      - "5432:5432"

  library:
    container_name: library
    build: .
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}