spring:
  application:
    name: Library

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/library
    username: POSTGRES_USERNAME
    password: POSTGRES_PASSWORD


  liquibase:
    change-log: db/changelog/main/main-changelog.yml
    enabled: true

  jpa:
    show-sql: true

server:
  port: ${SERVER_PORT}
